#  Configuration SonarQube
sonar.projectKey=portfolio-fullstack
sonar.projectName=Portfolio Full Stack - Mairam Baidy Sow
sonar.projectVersion=1.0

#  Sources à analyser
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,.git/**

#  Configuration SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_7a671bd11f4487006d4bce43b1489b585b28f502

#  Encodage
sonar.sourceEncoding=UTF-8
