apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
stringData:
  # Remplace la valeur ci-dessous par ta vraie URI MongoDB Atlas
  MONGO_URI: "mongodb+srv://USER:PASSWORD@cluster.mongodb.net/portfolio?retryWrites=true&w=majority"
